application: telobike
version: 5
runtime: python
api_version: 1

handlers:
- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin

- url: /stations(/.*)?
  script: stations_endpoint.py
  
- url: /history(/.*)?
  script: history_endpoint.py

- url: /cities(/.*)?
  script: cities_endpoint.py 

- url: /static
  static_dir: static

- url: /scripts
  static_dir: scripts

- url: /
  script: index.py
  
builtins:
- datastore_admin: on
- deferred: on
- remote_api: on
