application: telobike
version: 2
runtime: python
api_version: 1

handlers:
- url: /stations(/.*)?
  script: stations_endpoint.py
  
- url: /
  script: index.py
  

builtins:
- datastore_admin: on
- deferred: on
