application: telobike
version: 3
runtime: python
api_version: 1

handlers:
- url: /stations(/.*)?
  script: stations_endpoint.py

- url: /cities(/.*)?
  script: cities_endpoint.py 

- url: /
  script: index.py


builtins:
- datastore_admin: on
- deferred: on
