application: telobike
version: 4
runtime: python
api_version: 1

handlers:
- url: /stations(/.*)?
  script: stations_endpoint.py

- url: /cities(/.*)?
  script: cities_endpoint.py 

- url: /
  script: index.py

- url: /static
  static_dir: static

builtins:
- datastore_admin: on
- deferred: on
