source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '6.0'
inhibit_all_warnings!

pod 'AFNetworking'
pod 'SBJson'
pod 'Appirater'
pod 'GoogleAnalytics'
pod 'SVGeocoder'
pod 'InAppSettingsKit'
pod 'TTCounterLabel'

